"""Added photo_url to User and Updated Some Optional Fields

Revision ID: 91d391481a69
Revises: 2ae1e412fff0
Create Date: 2024-05-14 16:26:12.036285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d391481a69'
down_revision: Union[str, None] = '2ae1e412fff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('user', sa.Column('photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_url')
    op.alter_column('message', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
